version: "3.7"
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "C:/Paul/Programming/Java/RPKS6SEM/ServicesVolumes/ZookeeperVolume:/bitnami" #"zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    extra_hosts:
      - "host.docker.internal:host-gateway"


  kafka:
      image: docker.io/bitnami/kafka:3.4
      ports:
        - "9092:9092"
        - "9093:9093"
      volumes:
        - "C:/Paul/Programming/Java/RPKS6SEM/ServicesVolumes/KafkaVolume:/bitnami" #"kafka_data:/bitnami"

      environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
        - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://host.docker.internal:9093
        - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      depends_on:
        - zookeeper
      extra_hosts:
        - "host.docker.internal:host-gateway"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "workrules"
      POSTGRES_PASSWORD: "paul"
    volumes:
      - "C:/Paul/Programming/Java/RPKS6SEM/ServicesVolumes/PostgreSQLVolume/var/lib/postgresql/data:/mypg"
    ports:
      - '15432:5432'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - "C:/Paul/Programming/Java/RPKS6SEM/ServicesVolumes/RedisVolume/redis-data:/var/lib/redis"
    environment:
      - REDIS_REPLICATION_MODE=master
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongo:
    image: mongo:4.2.8
    ports:
      - "27017:27017"
    volumes:
      - "C:/Paul/Programming/Java/RPKS6SEM/ServicesVolumes/MongoDBVolume/mongo-data:/var/lib/mongo"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  filtering:
    image: filtering
    depends_on:
      - postgres
      - kafka
    extra_hosts:
      - "host.docker.internal:host-gateway"

  deduplication:
    image: deduplication
    depends_on:
      - redis
      - kafka
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

  enrichment:
    image: enrichment
    depends_on:
      - kafka
      - mongo
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
